// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type MemberTableRow = {
    id: string;
    email: string;
    role: { id: string; displayField: string };
    feedback: { nodes: FeedbackTableRow[] };
    name: string;
    comment1: { nodes: Comment1TableRow[] };
  };

  type FeedbackTableRow = {
    id: string;
    title: string;
    description: string;
    vote: number;
    slug: string;
    status: "ON PROGRESS" | "ICEBOX" | "DONE" | "TODO";
    createdBy: CreatedByTableRow;
    comment: { nodes: CommentTableRow[] };
    createdAt: Date;
  };

  type CommentTableRow = {
    id: string;
    body: string;
    createdAt: Date;
    feedback: FeedbackTableRow;
    createdBy: CreatedByTableRow;
  };

  type AllFeedbackViewRow = {
    read: {
      id: string;
      title: string;
      description: string;
      vote: number;
      slug: string;
      status: "ON PROGRESS" | "ICEBOX" | "DONE" | "TODO";
      createdBy: CreatedByTableRow;
      createdAt: Date;
    };
    write: {
      title: string;
      description: string;
      vote: number;
      slug: string;
      status: "ON PROGRESS" | "ICEBOX" | "DONE" | "TODO";
      createdBy: string[];
      createdAt: Date;
    };
    params: {};
    actions: {};
  };

  type AllMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      name: string;
    };
    write: {
      email: string;
      name: string;
    };
    params: {};
    actions: {};
  };

  type AllCommentViewRow = {
    read: {
      id: string;
      body: string;
      createdAt: Date;
      feedback: FeedbackTableRow;
      createdBy: CreatedByTableRow;
    };
    write: {
      body: string;
      createdAt: Date;
      feedback: string[];
      createdBy: string[];
    };
    params: {};
    actions: {};
  };

  type ProjectSchema = {
    allFeedback: AllFeedbackViewRow;
    allMember: AllMemberViewRow;
    allComment: AllCommentViewRow;
  };
}
