// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type MemberTableRow = {
    id: string;
    email: string;
    role: { id: string; displayField: string };
    feedback: { nodes: FeedbackTableRow[] };
    name: string;
    password: string;
  };

  type CommentTableRow = {
    id: string;
    body: string;
    feedback: FeedbackTableRow;
    createdAt: Date;
  };

  type FeedbackTableRow = {
    id: string;
    description: string;
    title: string;
    vote: number;
    createdBy: CreatedByTableRow;
    slug: string;
    createdAt: Date;
    status: "ON PROGRESS" | "DONE" | "ICEBOX" | "TODO";
    comment: { nodes: CommentTableRow[] };
    comments: string;
    numberofcomments: number;
    file: string;
  };

  type AllMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      name: string;
      password: string;
    };
    write: {
      email: string;
      name: string;
      password: string;
    };
    params: {};
    actions: {};
    forms: {
      formMember: {
        email?: string;
        role?: string;
      };
    };
  };

  type AllFeedbackViewRow = {
    read: {
      id: string;
      title: string;
      description: string;
      vote: number;
      createdBy: CreatedByTableRow;
      slug: string;
      createdAt: Date;
      status: "ON PROGRESS" | "DONE" | "ICEBOX" | "TODO";
      comments: string;
      numberofcomments: number;
      file: string;
    };
    write: {
      title: string;
      description: string;
      vote: number;
      createdBy: string[];
      slug: string;
      createdAt: Date;
      status: "ON PROGRESS" | "DONE" | "ICEBOX" | "TODO";
      file: string;
    };
    params: {};
    actions: { setdone: {} };
    forms: {
      feedbackForm: {
        title: string;
        description: string;
        createdBy: string[];
      };
    };
  };

  type AllCommentViewRow = {
    read: {
      id: string;
      body: string;
      feedback: FeedbackTableRow;
      createdAt: Date;
    };
    write: {
      body: string;
      feedback: string[];
      createdAt: Date;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type CommentsByFeedbackViewRow = {
    read: {
      id: string;
      body: string;
      feedback: FeedbackTableRow;
      createdAt: Date;
    };
    write: {
      body: string;
      feedback: string[];
      createdAt: Date;
    };
    params: {
      feedbackId: string;
    };
    actions: {};
    forms: {};
  };

  type ProjectSchema = {
    allMember: AllMemberViewRow;
    allFeedback: AllFeedbackViewRow;
    allComment: AllCommentViewRow;
    commentsByFeedback: CommentsByFeedbackViewRow;
  };
}
